### ISSUE TITLE
Package not found on Macos using gcc 

### ISSUE THREAD

**Issue by vamatya** [Exawind/build-test#6]
I tried both this repo as well as the one listed here: https://nalu.readthedocs.io/en/latest/source/user/build_spack.html

Following the instructions, I get the following error: 
Error: Package trilinos not found.

I also tried with/without python3 on the default path. 

I'm on High Sierra on mac, using gcc-7.3.0 built using spack.
Any suggestion/s what could be amiss?

**Comment by jrood-nrel** [comment]
@vamatya Sorry, for some reason I don't appear to be receiving emails for this repository. You should be able to see `trilinos` exists in Spack by `spack list trilinos`, or `spack info trilions`, and it should exist in `spack/var/spack/repos/builtin/packages/trilinos`. Can you confirm any of these are true? I've never experienced this error you see.

**Comment by vamatya** [comment]
@jrood-nrel `spack info trilinos` gives me the same error of package being not found. The spack version I'm using is 0.12.0. Thanks.

**Comment by jrood-nrel** [comment]
@vamatya Ah, that is a major problem then. Please use the `develop` branch of Spack and see if this resolves your problem. Spack moves so fast, the tagged versions become out-of-date quickly. However, even the 0.12.0 version of Spack should have Trilinos in it, so there might be a bigger problem on your system as well.

**Comment by vamatya** [comment]
@jrood-nrel You are correct. After updating spack to 0.12.1, I can now see trilinos packages. I'll repeat the process again. Thanks.

**Comment by jrood-nrel** [comment]
@vamatya I think you will need the `develop` branch of Spack. This is the recommended way to use Spack.

**Comment by vamatya** [comment]
@jrood-nrel I am on develop branch. It worked like a charm. Thanks!
