### ISSUE TITLE
Build with Spack fails fetching pkgconf, perl

### ISSUE THREAD

**Issue by cmkaul** [Exawind/build-test#7]
I am trying to build nalu-wind using spack on Eagle (as an external user of NREL HPC). I'm able to follow the instructions in the documentation up to the point of actually performing the install using install_nalu_eagle.sh but get errors such as:

==> Installing pkgconf
==> Searching for binary cache of pkgconf
==> Warning: No Spack mirrors are currently configured
==> No binary for pkgconf found: installing from source
==> Fetching http://distfiles.dereferenced.org/pkgconf/pkgconf-1.5.4.tar.xz

curl: (7) Failed to connect to 2602:ffdb:100:1::36: Network is unreachable
==> Fetching from http://distfiles.dereferenced.org/pkgconf/pkgconf-1.5.4.tar.xz failed.
==> Error: FetchError: All fetchers failed for pkgconf-1.5.4-3gir3hstuqku3ynuesgu32wo4naky4yn

I was able to circumvent this by creating a manual mirror for pkgcong. However I am now getting the same type of error for perl (and having trouble setting up a mirror for perl myself),  so it seems like there is perhaps some deeper problem.

==> Installing perl
==> Searching for binary cache of perl
==> Finding buildcaches in /home/ckaul/build-test/install-scripts/spack-mirror/build_cache
==> No binary for perl found: installing from source
==> Fetching file:///home/ckaul/build-test/install-scripts/spack-mirror/perl/perl-5.26.2.tar.gz
######################################################################## 100.0%
==> Fetching file:///home/ckaul/build-test/install-scripts/spack-mirror/perl/cpanm-5.26.2.tar.gz
curl: (37) Couldn't open file /home/ckaul/build-test/install-scripts/spack-mirror/perl/cpanm-5.26.2.tar.gz
==> Fetching from file:///home/ckaul/build-test/install-scripts/spack-mirror/perl/cpanm-5.26.2.tar.gz failed.
==> Fetching http://search.cpan.org/CPAN/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7042.tar.gz

curl: (7) Failed to connect to 2a04:4e42:2f::729: Network is unreachable
==> Fetching from http://search.cpan.org/CPAN/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7042.tar.gz failed.
==> Error: FetchError: All fetchers failed for resource-cpanm-c2rbjgnb5u7yybfnd64xc2bkfgrbhx6t

Any suggestions are very appreciated.

**Comment by sayerhs** [comment]
@cmkaul If you are attempting to run on NREL Eagle/Peregrine systems, all nalu-dependencies are installed by @jrood-nrel on the system, i.e., you don't need to do your own Spack install. You just just load all necessary modules and compile just `nalu-wind`

**Comment by jrood-nrel** [comment]
When it comes to downloading, this is something I don't wind up testing because I have several gigabytes of cached downloads. I have experienced many issues with SSL and Internet access on NREL machines, however. There used to be a `spack install -k` option that would help with the SSL problems, but I don't think that option exists anymore. Anyway, yes if you're on Eagle, we try to have everyone use exawind-builder now. Sometime I will move more of the documentation to reflect this.

**Comment by cmkaul** [comment]
Thanks for the suggestions, @sayerhs  and @jrood-nrel. I will try again with the exawind-builder scripts.

**Comment by cmkaul** [comment]
Using exawind-builder worked very nicely.  I'll go ahead and close this.
